### ISSUE TITLE
Idea for hashing pointers to unsized types

### ISSUE THREAD

**Issue by durka** [mbrubeck/by_address#2]
Can [this trick](https://play.rust-lang.org/?gist=b435f4e8f3123af87753c649353a3e95&version=stable) (essentially, compare `sizeof &T::Target` to `sizeof usize`) be used to eliminate the FIXME? https://github.com/mbrubeck/by_address/blob/3bdda92fb0160dc5473ed94c93b89fd163a0887e/src/lib.rs#L134-L138

**Comment by mbrubeck** [comment]
Yes, and I just landed that in libstd: rust-lang/rust#45483.

I'm wary about using it in this crate, since it depends on assumptions about the (implementation-defined) layout of pointers to unsized types.  My current plan is to wait until the implementation in libstd is stable, and then depend on that.
